function mm_report(m,c)
f=fopen(fullfile(c.output,'mission_report.md'),'w');cleanup=onCleanup(@()fclose(f));
fprintf(f,'# Mobile Manipulator: Measured Mission Report\n\n');
fprintf(f,'Generated by run_project from simulated state logs.\n\n');
fprintf(f,'| Measurement | Value |\n|---|---:|\n');
fprintf(f,'| Mission success | %d |\n| Duration (s) | %.3f |\n',m.completed,m.t(end));
fprintf(f,'| Collision samples (modeled bodies) | %d |\n| Minimum clearance (m) | %.6f |\n',m.collisionSamples,m.minClearance);
fprintf(f,'| Placement 1 error (m) | %.6f |\n| Placement 2 error (m) | %.6f |\n',m.placeError);
fprintf(f,'| Dock position error (m) | %.6f |\n| Dock heading error (rad) | %.6f |\n',m.dockError,m.dockYawError);
fprintf(f,'| Safety stop samples | %d |\n| Camera check passed | %d |\n',m.safetyStopSamples,m.inspection.passed);
fprintf(f,'| Total base travel (m) | %.3f |\n| AGV crossings | %d |\n| Scan duration (s) | %.2f |\n',m.routeLength,m.agvCrossingCount,c.scanDuration);
e=m.pathError(isfinite(m.pathError));fprintf(f,'| Navigation nearest-path RMS (m) | %.6f |\n',sqrt(mean(e.^2)));
fprintf(f,'\n## Event log\n');for i=1:numel(m.events),fprintf(f,'- %s\n',m.events{i});end
fprintf(f,'\n## Interpretation\nSuccess applies to this simplified simulated scene only. Collision monitoring uses conservative base circles and sampled arm/environment clearance; no gripper contact, wheel slip, full self-collision or safety certification. The wrist camera projects known block centroids and does not perform image-based recognition. Mission arm motion uses a joint acceleration servo with inverse-dynamics torque checks; run_experiments integrates torque-driven dynamics.\n');
end
